name_version = 'version_file_output' 


nside = 128
nstokes = 2

frequencies = [27, 39, 93, 145, 225, 280]

add_noise = true
filter_noise = true

[dictionary_minimiser]
   max_iter=100
   tol=1e-8
   solver_name="scipy_tnc"

   [dictionary_minimiser.options]
      min_steps=10
      cooldown=10
      verbose_print=true

[dictionary_parameters_CG]
   max_steps_CG=200
   tol_CG=1e-9


[path_inputs]

path_input_MSS2_obsmat = "/cephfs/soukdata/user_data/jost/MEGATOP/Obsmat/OBSMAT_TO_SOUK/MSS2/"

path_directory_input_MSS2_obsmat = "/cephfs/soukdata/user_data/jost/MEGATOP/Obsmat/OBSMAT_TO_SOUK/MSS2/"

path_nhits = "/cephfs/soukdata/user_data/jost/MEGATOP/Obsmat/OBSMAT_TO_SOUK/MSS2/sobs_RC1.r01_SAT4_mission_f030_4way_coadd_sky_ivar_healpix.fits"

path_N = "/shared_home/mag/MEGATOP/pixel_noisecov_preprocessed.npy"

path_output = '/cephfs/soukdata/user_scratch/mag/megabuster_playground/precomputations_tuto/'
# Both for outputs and input precomputations (assumed to be already done)

path_precomputations = '/cephfs/soukdata/user_scratch/mag/megabuster_playground/precomputations_tuto/'
